--sqlite

CREATE TABLE IF NOT EXISTS users(
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS posts(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ownerID INTEGER,
    title TEXT NOT NULL,
    content TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ownerID) REFERENCES users(ID) ON DELETE CASCADE
);
CREATE TABLE if NOT EXISTS votes(
    postID INTEGER NOT NULL,
    userID TEXT NOT NULL,
    FOREIGN KEY(userID) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY(postID) REFERENCES posts(ID) ON DELETE CASCADE,
    PRIMARY KEY(userID,postID)
);