--sqlite

CREATE TABLE IF NOT EXISTS users(
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS posts(
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    user INTEGER,
    title TEXT NOT NULL,
    content TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user) REFERENCES users(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS votes(
    post INTEGER NOT NULL,
    user TEXT NOT NULL,
    FOREIGN KEY(user) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY(post) REFERENCES posts(ID) ON DELETE CASCADE,
    PRIMARY KEY(user,post)
);