--psql

CREATE TABLE IF NOT EXISTS users(
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS posts(
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    userID TEXT,
    title TEXT NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(userID) REFERENCES users(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS votes(
    postID TEXT NOT NULL,
    userID TEXT NOT NULL,
    FOREIGN KEY(userID) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY(postID) REFERENCES posts(ID) ON DELETE CASCADE,
    PRIMARY KEY(userID,postID)
);